name: Publish to npm

on:
  push:
    branches: [ "main" ]
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          registry-url: https://registry.npmjs.org/
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm@latest

      - name: Install dependencies
        run: pnpm install
        
      - name: Run tests with pnpm
        run: pnpm test 

      - name: Build project with pnpm
        run: pnpm run build

      - name: Determine Bump Type
        id: bump-type
        run: |
          commit_msg=$(git log -1 --pretty=%B | grep -vE "ci|github-actions")
          
          if [[ "$commit_msg" == *"BREAKING CHANGE:"* || "$commit_msg" == *"feat:"* ]]; then
            echo "type=major" >> $GITHUB_OUTPUT
          elif [[ "$commit_msg" == *"fix:"* || "$commit_msg" == *"patch:"* ]]; then
            echo "type=patch" >> $GITHUB_OUTPUT
          elif [[ "$commit_msg" == *"chore:"* || "$commit_msg" == *"docs:"* || "$commit_msg" == *"style:"* || "$commit_msg" == *"refactor:"* ]]; then
            echo "type=minor" >> $GITHUB_OUTPUT  
          else
            echo "type=patch" >> $GITHUB_OUTPUT  
          fi
      - name: Set Git User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com" 
          
      - name: Bump Version
        run: |
          npm version ${{ steps.bump-type.outputs.type }} -m "chore: release v%s"
          new_version=$(node -p "require('./package.json').version")
          echo "New version: $new_version"
          
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config remote.origin.url "git@github.com:xianweics/seq-request.git"
      
      - name: Push Git Changes
        run: |
          git push origin main
      
      - name: Login to npm
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm whoami 
          
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  

